# -*- coding: utf-8 -*-
"""Algebraic_Functions.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dLIE9n9vytUzGs_EC4Eeqg18kg9-1Dlg

## Linear Function
"""

# Libraries
import matplotlib.pyplot as plt # Library for graphs
import numpy as np # Library for vectors and math utilities

N = 100 # Number of points

# f(x) = mx + b
def f(m, x, b):
  return m*x + b

# Slope 
m = (7-6)/(3-2)

x = np.linspace(-10.0, 10.0, num=N)

b = 10

# y = f(x)
y = f(m,x,b)

# Graph
fig, ax = plt.subplots()
ax.plot(x, y)
ax.grid()
ax.axhline(y = 0, color = 'r') # Horizontal line
ax.axvline(x = 0, color = 'r') # Vertical line

"""## Polynomial Function"""

def f(x):
  return 2*x**7 - x**4 + 3*x**2 + 4

x = np.linspace(-100.0, 100.0, num=N)

y = f(x)

# Graph
fig, ax = plt.subplots()
ax.plot(x, y)
ax.grid()
ax.axhline(y = 0, color = 'r') 
ax.axvline(x = 0, color = 'r')

