# -*- coding: utf-8 -*-
"""Designing_Maps.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1itS6UnCwiCDjHeBwJYROiHvo5aMZaQIa
"""

# Libraries
from matplotlib import cm # Handles colors
import matplotlib.pyplot as plt # Library for graphs
import numpy as np # Library for vectors and math utilities

"""## 3 Dimensions Graph"""

fig, ax = plt.subplots(subplot_kw={"projection": "3d"})


res = 100

X = np.linspace(-4, 4, res)
Y = np.linspace(-4, 4, res)

X, Y = np.meshgrid(X, Y)

Z = np.sin(X) + 2*np.sin(Y) 

# Plot the surface
surf = ax.plot_surface(X, Y, Z, cmap=cm.cool,
                       linewidth=0, antialiased=False)

fig.colorbar(surf)

"""## Level Curves"""

fig2,ax2 = plt.subplots()
level_map = np.linspace(np.min(Z), np.max(Z),res) 
cp = ax2.contour(X, Y, Z, levels=level_map,cmap=cm.cool)
fig2.colorbar(cp)
ax2.set_title('Level Curves')
plt.show()