# -*- coding: utf-8 -*-
"""Functions_Within_Functions.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1H18r0tRSgs-2MdpvywmKJTqdlHJobMZk
"""

# Libraries
import matplotlib.pyplot as plt # Library for graphs
import numpy as np # Library for vectors and math utilities

def g(x):
  return x**2

def f(x):
  return np.sin(x)

x = np.linspace(-10, 10, num=1000)

f_o_g = f(g(x))

# Graph 
fig, ax = plt.subplots()
ax.plot(x, f_o_g)
ax.grid()