# -*- coding: utf-8 -*-
"""Manipulating_Functions.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VyyK9hiC36sp6vRzP5AJ81UusVvC_Vw-

## Vertical and Horizontal Displacements
"""

# Libraries
import matplotlib.pyplot as plt # Library for graphs
import numpy as np # Library for vectors and math utilities

N = 100

def f(x):
  return x**2

c = 10

x = np.linspace(-15, 15, num=N)

y = f(x)

# Graph
fig, ax = plt.subplots()
ax.plot(x, y)
ax.grid()
ax.axhline(y = 0, color = 'r') # Horizontal line
ax.axvline(x = 0, color = 'r') # Vertical line

"""## Lengthening and Compressions"""

N = 1000

def f(x):
  return np.sin(x)

c = 3 

x = np.linspace(-15, 15, num=N)

y = f((1/1)*x)

# Graph
fig, ax = plt.subplots()
ax.plot(x, y)
ax.grid()
ax.axhline(y = 0, color = 'r') # Horizontal line
ax.axvline(x = 0, color = 'r') # Vertical line

"""## Reflections"""

N = 1000

def f(x):
  return x**3

x = np.linspace(-10, 10, num=N)

y = f(x)

# Graph
fig, ax = plt.subplots()
ax.plot(x, y)
ax.grid()
ax.axhline(y = 0, color = 'r') # Horizontal line
ax.axvline(x = 0, color = 'r') # Vertical line