# -*- coding: utf-8 -*-
"""Normal_Distribution.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19stdVYf1aM84dOrUlUGWCtF2RzLA5ziD
"""

# Libraries
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
from scipy.stats import norm

"""## Theoretical Normal Distribution


$$P(X) = \frac{1}{\sigma \sqrt{2 \pi}} \exp{\left[-\frac{1}{2}\left(\frac{X-\mu}{\sigma} \right)^2 \right]}$$

* $\mu$: Distribution Mean
* $\sigma$: Standard Deviation
"""

# We define our Gaussian distribution
def gaussean(x, mu, sigma):
  return 1/(sigma*np.sqrt(2*np.pi))*np.exp(-0.5*pow((x-mu)/sigma,2))

x = np.arange(-4,4,0.1)
y = gaussean(x, 0.0,1.0)

plt.plot(x,y)

# Calculating the Cumulative Distribution
dist = norm(0,1)
x = np.arange(-4,4,0.1)
y = [dist.cdf(value) for value in x]
plt.plot(x,y)



"""## Gaussian Distribution with Data

* Data set from https://seattlecentral.edu/qelp/sets/057/057.html
"""

df = pd.read_excel('s057.xls')
arr = df['Normally Distributed Housefly Wing Lengths'].values[4:]
values, dist = np.unique(arr, return_counts=True)
print(values)
plt.bar(values, dist)

# Probability Distribution Estimation
mu = arr.mean()

# Theorical Distribution
sigma = arr.std()
dist = norm(mu, sigma)
x = np.arange(30, 60, 0.1)
y = [dist.pdf(value) for value in x]
plt.plot(x,y)

# Data
values, dist = np.unique(arr, return_counts=True)
plt.bar(values, dist/len(arr))

